import type { Metadata } from "next";

import "./globals.css";
import HomePage from "@/pages";

export const metadata: Metadata = {
  title: "Third-work",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <HomePage />
        </div>
      </body>
    </html>
  );
}
